### ISSUE TITLE
UnicodeEncodeError raised by str.replace for certain tabs

### ISSUE THREAD

**Issue by ryanmcginnis** [alewin/CliChords#1]
Hi,

I thought you might be interested to know of a bug I found, and one solution. Certain tabs with Unicode characters (such as those written by a user of a European language) will fail with the following error:

`UnicodeEncodeError: 'ascii' codec can't encode character ...`

You can reproduce this in the following way:

1. Run tabs.py
2. Search for "leonard cohen the partisan" with quotation marks
3. Choose the fourth tab
4. Observe that the following error is raised: `UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 2238: ordinal not in range(128)`

One solution I found was to add `.encode('utf-8')` to the second line of the `get_tab` method, like so:

`tab = re.sub('\\r|\\t|<pre>|<span class="line_end">|<span>|</span>|<i>|</i>|</pre>|', "", tab).encode('utf-8')`

Additionally, I was happy to find that someone had written a program for scraping ultimate-guitar in this way. It was a project I wanted to write, too, and I learned from reading yours. Thanks!

Ryan

**Comment by alewin** [comment]
Thanks @ryanmcginnis 

Feel free to contribute and create pull request, if you want!
