### ISSUE TITLE
ultimate-guitar-scraper was shut down

### ISSUE THREAD

**Issue by Pilfer** [alewin/CliChords#3]
Just a heads up, but it looks like the `ultimate-guitar-scraper` repo and module got pulled at the request of a UG dev. Your repo is now mostly useless until you find another source.

**Comment by alewin** [comment]
@Pilfer I'll try to solve the problem these days, thank you

**Comment by Pilfer** [comment]
No problem. Best of luck!

**Comment by DaveGeneral** [comment]
have you solved it?
